import { LoginIcon, MailIcon, PaperAirplaneIcon, PhoneIcon } from '@heroicons/react/outline'
import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Footer from '../components/Footer'
import Link from 'next/link'

function About() {
    return (
        <div>
            <Head>
                <title>WingEd Girls | About</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon (1).ico" />
            </Head>
            <Header />
            <section className="relative h-[300px] md:h-[500px] xl:h-[800px]">
                    <Image src="/img (2).jpg" layout="fill" objectFit="cover"/>
                    <div className="absolute top-1/3 w-full text-center">
                        <p className="text-4xl md:text-3xl font-bold text-white">Get To Know Us</p>
                        
                    </div>
            </section>
            <main className="text-gray-500 max-w-7xl mx-auto px-5 sm:px-5">
                <section className=" py-10 text-center space-y-3">
                <p className="text-3xl">The Mission</p>
                <p>Our focus is on menstral health management, we distribute and teach girls in rural areas how make reusable pads. Our organisation also carries out talks to encourace girls to stay in school and choose career paths.</p>
                </section>
                <section className="p-3 mt-10 mb-20 relative h-[300px] space-y-3">
                    <Image src="/girls.jpg" layout="fill" objectFit="cover" className="rounded-xl"/>
                    <div className="relative top-16 space-y-3">
                        <h1 className="text-3xl text-white font-bold">Support Our Cause</h1>
                        
                        <Link href="/contact" ><button className="bg-pink-500 text-white rounded-2xl p-3">Donate</button></Link>
                    </div>  
                </section>
            </main>
            <Footer />
        </div>
    )
}

export default About
