import { LockClosedIcon, LoginIcon, MailIcon, PaperAirplaneIcon, PhoneIcon } from '@heroicons/react/outline'
import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Footer from '../components/Footer'
import { useState } from 'react'
import Link from 'next/link'
import Cookies from 'cookies'
import {useRouter} from 'next/router'
import { getCookie } from 'cookies-next';
import axios from 'axios'



function Contact(props) {
    const [openModal, setOpenModal] = useState(false)
   
    console.log(props)
    const blogs = props.d.data
    console.log(blogs)
    
    return (
        <div>
             <Head>
                <title>WingEd Girls | Blogs</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon (1).ico" />
            </Head>
            <Header />
            <section className="relative h-[300px] md:h-[500px] xl:h-[800px]">
                    <Image src="/img (2).jpg" layout="fill" objectFit="cover" alt="image"/>
                    <div className="absolute top-1/3 w-full text-center">
                        <p className="text-4xl md:text-3xl font-bold text-white">Blogs and News</p>
                        
                    </div>
            </section>
            <main className="text-gray-500 max-w-7xl mx-auto px-5 sm:px-5">
                <section className="py-5">
                    <p className="text-4xl py-10">Top Blogs</p>
                    <div className="grid grid-cols-1 lg:grid-cols-3 gap-3">
                        {
                            blogs.map(data => {
                                return( <>
                                <div className="bg-gray-100  w-full rounded-2xl space-y-3">
                                <div className="relative h-44 w-full ">
                                    <Image src="https://i.postimg.cc/rpRYZcND/pexels-sourav-mishra-1149831.jpg" className="rounded-2xl" alt="image" layout="fill" objectFit="cover"/>
                                </div>
                                <div className="space-y-3 p-2">
                                    <h1 className="text-3xl font-bold">{data.title}</h1>
                                    <div className="divider p-1 bg-pink-500 w-10"></div>
                                    <p>{data.description}</p>
                                    {/* <p >By: {data.user}</p> */}
                                    <button className="p-4 text-white bg-pink-500 w-full rounded-2xl">Read Blog</button>
                                </div>
                            </div> </>)
                            })
                        }
                    </div>
                </section>
            </main>
            <Footer />
            {openModal ? (
                    <>
                    <div
                    className="justify-center  items-center flex overflow-x-hidden overflow-y-auto fixed inset-0 z-50 outline-none focus:outline-none ease-linear transition-all duration-150 text-gray-500"
                    >
                    <div className="relative my-6 mx-auto w-96">
                        {/*content*/}
                        <div className="border-0 rounded-lg shadow-lg relative flex flex-col w-full bg-white outline-none focus:outline-none h-auto overflow-auto text-sm">
                        {/*header*/}
                        <div className="flex items-start justify-between p-5 border-b border-solid border-blueGray-200 rounded-t">
                            <h3 className="text-xl font-semibold text-pink-500">
                                Support this cause
                            </h3>
                            <button
                            className="p-1 ml-auto bg-transparent border-0 text-black opacity-5 float-right text-3xl leading-none font-semibold outline-none focus:outline-none"
                            onClick={() => setShowModal1(false)}
                            >
                            <span className="bg-transparent text-black opacity-5 h-6 w-6 text-2xl block outline-none focus:outline-none">
                                <LockClosedIcon className="text-pink-500 h-8" />
                            </span>
                            </button>
                        </div>
                        {/*body*/}
                        <div className="relative p-6 flex-auto">
                            <p>Kindly Send your donations to the numbers below. Or you can contact us at wingedgirlszm@gmail.com</p>
                            <br></br>
                            <p>+260 96 6245070</p>
                            <p>+260 97 3757535</p>

                        </div>
                        {/*footer*/}
                        <div className="flex items-center justify-end p-6 border-t border-solid border-blueGray-200 rounded-b">
                            <button
                            className="bg-pink-500 font-bold uppercase px-6 py-3 rounded-2xl text-white text-sm outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150"
                            type="button"
                            onClick={() => setOpenModal(false)}
                            >
                            Close
                            </button>
                            
                        </div>
                        </div>
                    </div>
                    </div>
                    <div className="opacity-25 fixed inset-0 z-40 bg-black"></div>
                </>
                ) : null
            }
            
        </div>
    )
}
export async function getServerSideProps(context){
    const cookies = new Cookies(context.req, context.res)
    const token = cookies.get('token')

    const data = await axios.get('https://wingedgirls.herokuapp.com/api/v1/blogs', {
        headers: {
            'Content-Type': 'application/json',
            accept: '*/*',
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${token}`
          }
    })
    const d = data.data
    console.log(d)
    return {
        props: {
            d
        }
    }
}

export default Contact
