import { LoginIcon, MailIcon, PaperAirplaneIcon, PhoneIcon } from '@heroicons/react/outline'
import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Footer from '../components/Footer'
import { useState } from 'react'


function Contact() {
    const [input, setInput] = useState('')
    const subscribe = async (e) => {
        e.preventDefault() // prevents page reload
        try {
            const res = await fetch('./api/subscribe', {
              method: 'post',
              headers: {
                'Content-Type': 'application/json'
              },
              body: JSON.stringify({
                emailAddress: input
              })
            })
            
            if (res.status === 200) {
              alert('You are subscribed!')
            } else {
              alert('Sorry, something went wrong.')
            }
          } catch(err) {
            alert('Sorry, something went wrong.')
          }
      }
    return (
        <div>
             <Head>
                <title>WingEd Girls | Welcome</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon (1).ico" />
            </Head>
            <Header />
            <section className="relative h-[300px] md:h-[500px] xl:h-[800px]">
                    <Image src="/img (2).jpg" layout="fill" objectFit="cover"/>
                    <div className="absolute top-1/3 w-full text-center">
                        <p className="text-4xl md:text-3xl font-bold text-white">Reach Out To Us</p>
                        
                    </div>
            </section>
            <main className="text-gray-500 max-w-7xl mx-auto px-5 sm:px-5">
                <section className="py-5">
                    <p className="text-3xl text-center p-2">Contacts and Details</p>
                    <div className="grid grid-cols-1 md:grid-cols-2">
                        <div className="p-2 m-4 flex flex-col items-center justify-center h-62 shadow-md rounded-2xl border border-gray-100">
                            <div className="relative h-24 w-24 border-4 border-pink-500 rounded-full">
                             <Image src="/pamela.jpeg" className=" rounded-full" layout="fill" objectFit="cover"/>
                            </div>
                            <div className="flex flex-col items-center p-2">
                                <p className="font-bold">Pamela</p>
                                <p className="text-sm">Co-Founder</p>
                            </div>
                            <div className="flex space-x-3">
                                <a className="p-3 bg-pink-500 rounded-full text-white" href="tel:260973757535"><PhoneIcon className="h-6 w-6"/></a>
                                <a className="p-3 bg-pink-500 rounded-full text-white" href="mailto:wingedgirlszm.@gmail.com"><MailIcon className="h-6 w-6"/></a>
                            </div>
                        </div>
                        <div className="p-2 m-4 flex flex-col items-center justify-center h-62 shadow-md rounded-2xl border border-gray-100">
                            <div className="relative h-24 w-24 border-4 border-pink-500 rounded-full">
                             <Image src="/mwape.jpeg" className=" rounded-full" layout="fill" objectFit="cover"/>
                            </div>
                            <div className="flex flex-col items-center p-2">
                                <p className="font-bold">Mwape Kapepula</p>
                                <p className="text-sm">Co-Founder</p>
                            </div>
                            <div className="flex space-x-3">
                                <a className="p-3 bg-pink-500 rounded-full text-white" href="tel:260966245070"><PhoneIcon className="h-6 w-6"/></a>
                                <a className="p-3 bg-pink-500 rounded-full text-white" href="mailto:wingedgirlszm.@gmail.com"><MailIcon className="h-6 w-6"/></a>
                            </div>
                        </div>
                    </div>
                </section>
                <section className="">
                    <p className="text-3xl text-center p-2">Be on our mailing list</p>
                    <div className='p-8 justify-center items-center flex'>
                        <form className='flex p-2 border border-pink-500 rounded-full'>
                            <input  value={input} onChange={e => setInput(e.target.value)} className='p-2 flex-1 outline-none' id='email' type='email' aria-label='email address' placeholder='Enter your email address' />
                            <button onClick={subscribe} className='bg-pink-500 rounded-full hover:bg-blue-700 duration-300 text-white shadow p-2' type='submit'>
                                <PaperAirplaneIcon className='h-6 w-6 rotate-90'/>
                            </button>
                        </form>
                    </div>

                </section>
            </main>
            <Footer />
            
        </div>
    )
}

export default Contact
