import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/Banner'
import Header from '../components/Header'
import MedCard from '../components/MedCard'
import Footer from '../components/Footer'
import { LockClosedIcon, MailIcon, PhoneIcon } from '@heroicons/react/outline'
import { useState } from 'react'

export default function Home({data,data2}) {
  const [openModal, setOpenModal] = useState(false)
    const open = (e) =>{
        e.preventDefault()
        setOpenModal(true)
    }
  
  return (
    <div className="">
      <Head>
        <title>WingEd Girls | Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon (1).ico" />
      </Head>

      
        {/* Header Start*/}
        <Header/>
        {/* Header End */}

        {/* Banner Start */}
        <Banner/>
        {/* Banner End */}
      <main className="text-gray-500 max-w-7xl mx-auto px-8 sm:px-16">
        <section className="pt-12 " id="about">
          <h2 className="text-4xl mb-6 text-center">WingEd Girls</h2>
          <div className="grid grid-cols-1 text-center">
            {/* Pull data from server */}
            <p>Our focus is on menstral health management, we distribute and teach girls in rural areas how make reusable pads. Our organisation also carries out talks to encourace girls to stay in school and choose career paths.</p>
            {/* {data?.map(place=>{
              return (
                <PlacesCard key={place.img} image={place.img} distance={place.distance} location={place.location}/>
              )
            })} */}
          </div>
          <h2 className="text-4xl mb-6 mt-16 text-center">The Team</h2>
          <div className="grid grid-cols-1 md:grid-cols-2">
              <div className="p-2 m-4 flex flex-col items-center justify-center h-62 shadow-md rounded-2xl border border-gray-100">
                  <div className="relative h-24 w-24 border-4 border-pink-500 rounded-full">
                    <Image src="/pamela.jpeg" className=" rounded-full" layout="fill" objectFit="cover"/>
                  </div>
                  <div className="flex flex-col items-center p-2">
                      <p className="font-bold">Pamela</p>
                      <p className="text-sm">Co-Founder</p>
                      <p className="text-sm">+260 97 3757535</p>
                  </div>
                  {/* <div className="flex space-x-3">
                      <a className="p-3 bg-pink-500 rounded-full text-white" href="tel:260973757535"><PhoneIcon className="h-6 w-6"/></a>
                      <a className="p-3 bg-pink-500 rounded-full text-white" href="mailto:wingedgirlszm.@gmail.com"><MailIcon className="h-6 w-6"/></a>
                  </div> */}
              </div>
              <div className="p-2 m-4 flex flex-col items-center justify-center h-62 shadow-md rounded-2xl border border-gray-100">
                  <div className="relative h-24 w-24 border-4 border-pink-500 rounded-full">
                    <Image src="/mwape.jpeg" className=" rounded-full" layout="fill" objectFit="cover"/>
                  </div>
                  <div className="flex flex-col items-center p-2">
                      <p className="font-bold">Mwape Kapepula</p>
                      <p className="text-sm">Co-Founder</p>
                      <p className="text-sm">+260 96 6245070</p>
                  </div>
                  {/* <div className="flex space-x-3">
                      <a className="p-3 bg-pink-500 rounded-full text-white" href="tel:260966245070"><PhoneIcon className="h-6 w-6"/></a>
                      <a className="p-3 bg-pink-500 rounded-full text-white" href="mailto:wingedgirlszm.@gmail.com"><MailIcon className="h-6 w-6"/></a>
                  </div> */}
              </div>
          </div>
        </section>
        <section className="pt-16" id="contact">
          <h2 className="text-4xl text-center">Our Pages</h2>
          {/* <p className="text-2xl mt-4">Our Social</p> */}
          <div className="grid grid-cols-1 md:grid-cols-4 space-x-2 mt-8">
            
            <div className="flex flex-col p-2 rounded-2xl items-center mt-2">
                <a href="https://www.facebook.com/wingedgirlszm/?ref=page_internal" className="">
                <div className="h-24 w-24 bg-pink-500 rounded-full flex items-center justify-center">
                  <Image src="/fb.png" height={60} width={60}/>
                </div>
                </a>
                <p className="mt-4 font-bold">Facebook</p>
                <p className="text-sm">@wingedgirlszm</p>
            </div>
            <div className="flex flex-col p-2 rounded-2xl items-center mt-2">
              <a href="https://www.instagram.com/wingedgirlszm/?utm_medium=copy_link&fbclid=IwAR1M5xbC5cmwkY2XTLCgyAnSr5_RpFn9WWqIys5KJWOElaTuizpBIQqyRAc" className="">
                <div className="h-24 w-24 bg-pink-500 rounded-full flex items-center justify-center">
                <Image src="/insta.png" height={60} width={60}/>
                </div>
              </a>
                <p className="mt-4 font-bold">Instagram</p>
                <p className="text-sm">@wingedgirlszm</p>
            </div>
            <div className="flex flex-col p-2 rounded-2xl items-center mt-2">
            <div className="h-24 w-24 bg-pink-500 rounded-full flex items-center justify-center">
                  <Image src="/email.png" height={60} width={60}/>
                </div>
                <p className="mt-4 font-bold">Email</p>
                <p className="text-sm">wingedgirlszm@gmail.com</p>
            </div>
            <div className="flex flex-col p-2 rounded-2xl items-center mt-2">
            <div className="h-24 w-24 bg-pink-500 rounded-full flex items-center justify-center">
                <Image src="/phone.png" height={60} width={60}/>
                </div>
                <p className="mt-4 font-bold">Mobile</p>
                <p className="text-sm">+260973757535</p>
            </div>
          </div>
          {/* <h1 className="text-4xl mt-1 text-center" id="ourwork">Our Work</h1> */}
          <div className="">
         
                {/* <Mailchimp
              action='https://gmail.us20.list-manage.com/subscribe/post?u=ac601dc4870e4def22bbd33e3&amp;id=72b52cf1bb'
              fields={[
                {
                  name: 'EMAIL',
                  placeholder: 'Email',
                  type: 'email',
                  required: true
                }
              ]}
              /> */}
          </div>
          {/* <div className="flex p-3 overflow-auto space-x-3 py-3 scrollbar-hide w-full mt-10" id="donate">
            {
              data2?.map(data=>{
                return (
                  <MedCard key={data.img} image={data.img} title={data.title}/>
                )
              })
            }
          </div> */}
        </section>
        <section className="p-3 mt-20 mb-20 relative h-[300px] space-y-3">
            <Image src="/girls.jpg" layout="fill" objectFit="cover" className="rounded-xl"/>
          <div className="relative top-16 space-y-3">
            <h1 className="text-3xl text-white font-bold">Support Our Cause</h1>
            
            <button onClick={open} className="bg-pink-500 text-white rounded-2xl p-3">Donate</button>
          </div>
        </section>
      </main>
      <Footer />
      {openModal ? (
                    <>
                    <div
                    className="justify-center  items-center flex overflow-x-hidden overflow-y-auto fixed inset-0 z-50 outline-none focus:outline-none ease-linear transition-all duration-150 text-gray-500"
                    >
                    <div className="relative my-6 mx-auto w-96">
                        {/*content*/}
                        <div className="border-0 rounded-lg shadow-lg relative flex flex-col w-full bg-white outline-none focus:outline-none h-auto overflow-auto text-sm">
                        {/*header*/}
                        <div className="flex items-start justify-between p-5 border-b border-solid border-blueGray-200 rounded-t">
                            <h3 className="text-xl font-semibold text-pink-500">
                                Support this cause
                            </h3>
                            <button
                            className="p-1 ml-auto bg-transparent border-0 text-black opacity-5 float-right text-3xl leading-none font-semibold outline-none focus:outline-none"
                            onClick={() => setShowModal1(false)}
                            >
                            <span className="bg-transparent text-black opacity-5 h-6 w-6 text-2xl block outline-none focus:outline-none">
                                <LockClosedIcon className="text-pink-500 h-8" />
                            </span>
                            </button>
                        </div>
                        {/*body*/}
                        <div className="relative p-6 flex-auto">
                            <p>Kindly Send your donations to the numbers below. Or you can contact us at wingedgirlszm@gmail.com</p>
                            <br></br>
                            <p>+260 96 6245070</p>
                            <p>+260 97 3757535</p>

                        </div>
                        {/*footer*/}
                        <div className="flex items-center justify-end p-6 border-t border-solid border-blueGray-200 rounded-b">
                            <button
                            className="bg-pink-500 font-bold uppercase px-6 py-3 rounded-2xl text-white text-sm outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150"
                            type="button"
                            onClick={() => setOpenModal(false)}
                            >
                            Close
                            </button>
                            
                        </div>
                        </div>
                    </div>
                    </div>
                    <div className="opacity-25 fixed inset-0 z-40 bg-black"></div>
                </>
                ) : null
            }
      
    </div>
  )
}

export async function getStaticProps(){
  const data = await fetch(`https://links.papareact.com/pyp`).then(res=>{
    return res.json()
  })

  const data2 = await fetch(`https://links.papareact.com/zp1`).then(res=>{
    return res.json()
  })

  return {
    props: {
      data,
      data2
    }
  }
}
